### ISSUE TITLE
 Mention cheatsheet and comparison repo

### ISSUE THREAD

**Issue by michielbdejong** [jeff-zucker/solid-libraries#5]
This list can link to https://vincenttunru.gitlab.io/tripledoc/docs/cheatsheet and https://github.com/inrupt/solid-lib-comparison

Fixed in #2.

**Comment by jeff-zucker** [comment]
My thought is that there should be a list of libraries (this page) and also an overview page which points to the list and to other resources including cheatsheets, and tutorials.  So I would prefer not to mix those in with the list of libraries
